name: Run Daily Scraper

on:
  # This lets you run it manually from the "Actions" tab
  workflow_dispatch:
  
  # This runs it on a schedule
  schedule:
    # Runs at 6:00 UTC every day (11:30 AM India Time)
    - cron: '0 6 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Match your local version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the scraper
        run: python scraper.py
        env:
          # This securely injects your database password
          DATABASE_URL: ${{ secrets.DATABASE_URL }}